apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
  labels: 
    app: mongodb
    chart: mongodb-7.8.10
    heritage: Tiller
    release: velocity-mongo
spec:
  storageClassName: local-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: velocity-mongo-mongodb
  nfs:
    path: /tmp
    server: 172.17.0.2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["ip-192-168-1-80.ec2.internal"]
