apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
spec:
  storageClassName: local-storage
 capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: velocity-mongo-mongodb
  nfs:
    path: /tmp
    server: 172.17.0.2
